export const SIGNIN_INSTRUCTOR = 'SIGNIN_INSTRUCTOR';
export const SIGNIN_CLIENT = 'SIGNIN_CLIENT';
export const ADD_CLASSES = 'ADD_CLASSES';
export const EDIT_CLASSES = 'EDIT_CLASSES';
export const DELETE_CLASSES = 'DELETE_CLASSES';
export const SIGNUP_FOR_CLASSES = 'SINGUP_FOR_CLASSES';
export const DROP_CLASSES = 'DROP_CLASSES';
